### PR TITLE
Fix: file name for JunitXmlReporter #50

### LINKED ISSUE #50: [BUG] JUnit Reporter path name is too long
### What is the bug?
The path name is too long, so the JUnit Xml Reporter cannot create a xml file with the results.
For example: `Exception during run: Error: ENAMETOOLONG: name too long, open 'test-results/htmlSanityCheck/TEST-unit-html-target_generated-docs_lfet-maven-plugin_latest_calist_Goal_CAList_-_creating_condition_and_action_list_of_decision_tables_LF-ET.xml'`

### How can one reproduce the bug?
Create a deep nested structure or create html files with extra long name.

### What is the expected behavior?
I think it isn't necessary to use the file name for the result file. Use only a uuid for the result files.

### What is your host/environment?
Linux Mint

### Do you have any screenshots?
`Exception during run: Error: ENAMETOOLONG: name too long, open 'test-results/htmlSanityCheck/TEST-unit-html-target_generated-docs_lfet-maven-plugin_latest_calist_Goal_CAList_-_creating_condition_and_action_list_of_decision_tables_LF-ET.xml'`

### Do you have any additional context?
No

### PR DESCRIPTION
**Pull request by uniqueck**
### Description
Solve the bug described in #50 and act more like original htmlsanitycheck project.

### Issues Resolved
Fixes #50

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: lib/reporter/JUnitXmlReporter.js [hunk 1]
```diff
@@ -43,16 +43,18 @@ class JUnitXmlReporter extends Reporter {
...
-    // https://github.com/aim42/htmlSanityCheck/blob/main/src/main/groovy/org/aim42/htmlsanitycheck/report/JUnitXmlReporter.groovy#L54
+    // https://github.com/aim42/htmlSanityCheck/blob/main/htmlSanityCheck-core/src/main/java/org/aim42/htmlsanitycheck/report/JUnitXmlReporter.java#L99-L104
     // Determine the name based on available properties or generate a UUID
-    const nameParts = []
-    nameParts.push(pageResult.pageFilePath)
-    if (pageResult.pageTitle) {
-      nameParts.push(pageResult.pageTitle)
+    let name = ''
+    if (pageResult.pageFilePath) {
+      name = `${pageResult.pageFilePath}_${pageResult.pageFileName}`
```
Comment (shoelzle) [inline lib/reporter/JUnitXmlReporter.js:50]: With the solution, a too long file name can still be created, or not?

What about a simpler solution?
For example, just always use the filename with a UUID as suffix.

But I guess your solution is better than before, so it's OK for me if you merge your solution.

**Review by shoelzle — APPROVED** [review]

File: lib/reporter/JUnitXmlReporter.js (hunk 1 above)
Comment (uniqueck) [reply lib/reporter/JUnitXmlReporter.js]: So I think the simplest approach is this best.

**Review by shoelzle — APPROVED** [review]
